In [3]:
import numpy as np

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [ ]:
# Exercise 1 - How many negative numbers are there?

In [5]:
new_array = a[a < 0]
new_array

array([-2, -1, -6, -7])

In [6]:
len(new_array)

4

In [ ]:
# Exercise 2 - How many positive numbers are there?

In [7]:
new_array = a[a > 0]
new_array

array([ 4, 10, 12, 23,  3])

In [8]:
len(new_array)

5

In [ ]:
# Exercise 3 - How many positive numbers are there?

In [9]:
new_array = a[a % 2 == 0]
newest_array = new_array[new_array > 0]
newest_array

array([ 4, 10, 12])

In [10]:
len(newest_array)

3

In [ ]:
# Exercise 4 - If you were to add 3 to each data point, how many positive numbers would there be?

In [11]:
new_array = a + 3
new_array

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [12]:
len(new_array[new_array > 0])

10

In [ ]:
# Exercise 5 - If you squared each number, what would the new mean and standard deviation be?

In [10]:
new_array = a ** 2
new_array

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [14]:
new_array.std()

144.0243035046516

In [15]:
new_array.mean()

74.0

In [ ]:
# Exercise 6 - A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. Center the data set.

In [38]:
center = lambda a: a - a.mean()
a_centered = center(a)
print(a_centered.mean())

0.0


In [ ]:
# Calculate the z-score for each data point

In [44]:
b = a
mean = np.mean(b)
std = np.std(b)
z = (b - mean)/std
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])